- id: '1688111538910'
  alias: Litière Intelligente - Incrementer passages litière
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_litiere
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_clean_cat_litter_box
    state: 'on'
  action:
  - service: input_number.increment
    data: {}
    target:
      entity_id: input_number.litter_tracking
  mode: single
- id: '1688112377959'
  alias: Litière Intelligente - Notifier litière pleine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.is_litter_full
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_clean_cat_litter_box
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_when_present
      title: "\U0001F408  Litière"
      message: Penser a nettoyer la litière !
      callback:
      - title: Litière Nettoyée
        event: reset_litter_tracking
      icon: mdi:cat
      color: deep-orange
      persistent: true
      tag: litter_full
      until:
      - entity_id: binary_sensor.is_litter_full
        new_state: 'off'
  mode: single
- id: '1688112671844'
  alias: Litière Intelligente - Remettre à zero passages litière
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: reset_litter_tracking
  condition:
  - condition: state
    entity_id: input_boolean.automation_clean_cat_litter_box
    state: 'on'
  action:
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.litter_tracking
  mode: single
- id: '1688114260897'
  alias: Poubelles Intelligentes - Informer poubelle noire à sortir
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_noire
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.poubelle_noire_a_sortir
  mode: single
- id: '1688114327500'
  alias: Poubelles Intelligentes - Informer poubelle verte à sortir
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_verte
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.poubelle_verte_a_sortir
  mode: single
- id: '1688114732811'
  alias: Poubelles Intelligentes - Notifier poubelle noir non sortie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_noire
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  - condition: state
    entity_id: input_boolean.poubelle_noire_a_sortir
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_to_present
      title: "\U0001F5D1 Poubelle Noire"
      message: N'oublie pas de sortir la poubelle noire
      icon: mdi:delete
      color: deep-orange
      tag: black_trash
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.poubelle_noire_a_sortir
  mode: single
- id: '1688114808231'
  alias: Poubelles Intelligentes - Notifier poubelle verte non sortie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_verte
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  - condition: state
    entity_id: input_boolean.poubelle_verte_a_sortir
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_to_present
      title: ♻️ Poubelle Verte
      message: N'oublie pas de sortir la poubelle verte
      icon: mdi:recycle
      color: deep-orange
      tag: green_trash
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.poubelle_verte_a_sortir
  mode: single
- id: '1688116237944'
  alias: 'Boîte aux Lettres Intelligente - Notifier courrier '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_boite_aux_lettres
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_monitor_mailbox
    state: 'on'
  - condition: state
    entity_id: binary_sensor.is_front_door_recently_open
    state: 'off'
  action:
  - event: NOTIFIER
    event_data:
      action: send_when_present
      title: "\U0001F4EC  Boite aux lettres"
      message: Vous avez du courrier !
      icon: mdi:mailbox-up
      color: green
      tag: you_got_mail
  mode: single
- id: '1688116301973'
  alias: Boîte aux Lettres Intelligente - Supprimer notification courrier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_boite_aux_lettres
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_monitor_mailbox
    state: 'on'
  - condition: state
    entity_id: binary_sensor.is_front_door_recently_open
    state: 'on'
  action:
  - event: NOTIFIER_DISCARD
    event_data:
      tag: you_got_mail
  mode: single
- id: '1688117249626'
  alias: Boutons Hue - Bouton ON Entrée maintenu appuyé
  description: ''
  trigger:
  - device_id: 64185ca2086c2ebd7b976a43ef0c89fd
    domain: hue
    platform: device
    type: repeat
    subtype: 1
    unique_id: c1c9f277-e27a-4340-9962-2206cc0d7e3a
  condition: []
  action:
  - service: script.reset_lights_day_area
    data: {}
  mode: single
- id: '1688117356091'
  alias: Boutons Hue - Bouton OFF Entrée maintenu appuyé
  description: ''
  trigger:
  - device_id: 64185ca2086c2ebd7b976a43ef0c89fd
    domain: hue
    platform: device
    type: repeat
    subtype: 4
    unique_id: 7564eab9-3cc9-4321-890c-1b9f1465f108
  condition: []
  action:
  - service: script.leave_home
    data: {}
  mode: single
- id: '1688117431729'
  alias: Boutons Hue - Bouton ON Salon Couloir maintenu appuyé
  description: ''
  trigger:
  - device_id: efa42240bac38d83b77963e7fd5bb5ac
    domain: hue
    platform: device
    type: repeat
    subtype: 1
    unique_id: 9df3f0e5-001b-4c7b-9c5d-a96a8b391edd
  condition: []
  action:
  - service: script.reset_lights_day_area
    data: {}
  mode: single
- id: '1688117473124'
  alias: Boutons Hue - Bouton OFF Salon Couloir maintenu appuyé
  description: ''
  trigger:
  - device_id: efa42240bac38d83b77963e7fd5bb5ac
    domain: hue
    platform: device
    type: repeat
    subtype: 4
    unique_id: 73e97207-29d2-4078-8304-9e918425fe48
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.lumieres_rez_de_chaussee
      - light.exterieur
  mode: single
- id: '1688118075093'
  alias: Machine a Laver Intelligente - Notifier cycle de lavage terminé
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.is_washing_machine_running
    to: 'off'
    from: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_monitor_washing_machine
    state: ''
  action:
  - event: NOTIFIER
    event_data:
      action: send_when_present
      title: "\U0001FAE7 Machine à laver"
      message: Cycle de lavage terminé !
      icon: mdi:washing-machine
      color: green
      tag: washing_mashine_over
  mode: single
- id: '1688124199640'
  alias: Bienvenue lumineux - Allumer lumières quand porte ouverte
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.home_occupied
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_welcome_home
    state: 'on'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.capteur_ouverture_porte_entree
      to: 'on'
    timeout:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - service: hue.activate_scene
    data:
      transition: 3
    target:
      entity_id: scene.entree_entree_100
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: hue.activate_scene
    data:
      transition: 3
    target:
      entity_id:
      - scene.salon_salon_100
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: hue.activate_scene
    data:
      transition: 3
    target:
      entity_id: scene.cuisine_cuisine_100
  mode: single
