- id: '1688111538910'
  alias: Litière Intelligente - Incrementation des passages dans la litière
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_litiere
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_clean_cat_litter_box
    state: 'on'
  action:
  - service: input_number.increment
    data: {}
    target:
      entity_id: input_number.litter_tracking
  mode: single
- id: '1688112377959'
  alias: Litière Intelligente - Notification litière pleine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.is_litter_full
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_clean_cat_litter_box
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_when_present
      title: "\U0001F408  Litière"
      message: Penser a nettoyer la litière !
      callback:
      - title: Litière Nettoyée
        event: reset_litter_tracking
      icon: mdi:cat
      color: deep-orange
      persistent: true
      tag: litter_full
      until:
      - entity_id: binary_sensor.is_litter_full
        new_state: 'off'
  mode: single
- id: '1688112671844'
  alias: Litière Intelligente - Remise à zero de nombre de passage
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: reset_litter_tracking
  condition:
  - condition: state
    entity_id: automation.litter_automation_reset
    state: 'on'
  action:
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.litter_tracking
  mode: single
- id: '1688114260897'
  alias: Poubelles Intelligentes - Poubelle noire à sortir
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_noire
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.poubelle_noire_a_sortir
  mode: single
- id: '1688114327500'
  alias: Poubelles Intelligentes - Poubelle verte à sortir
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_verte
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.poubelle_verte_a_sortir
  mode: single
- id: '1688114732811'
  alias: Poubelles Intelligentes - Notification poubelle noir non sortie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_noire
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  - condition: state
    entity_id: input_boolean.poubelle_noire_a_sortir
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_to_present
      title: "\U0001F5D1 Poubelle Noire"
      message: N'oublie pas de sortir la poubelle noire
      icon: mdi:delete
      color: deep-orange
      tag: black_trash
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.poubelle_noire_a_sortir
  mode: single
- id: '1688114808231'
  alias: Poubelles Intelligentes - Notification poubelle verte non sortie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.planning_poubelle_verte
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.automation_take_out_trash
    state: 'on'
  - condition: state
    entity_id: input_boolean.poubelle_verte_a_sortir
    state: 'on'
  action:
  - event: NOTIFIER
    event_data:
      action: send_to_present
      title: ♻️ Poubelle Verte
      message: N'oublie pas de sortir la poubelle verte
      icon: mdi:recycle
      color: deep-orange
      tag: green_trash
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.poubelle_verte_a_sortir
  mode: single
