# DEFAULT

default_config:

api:

# MISC
http: !include misc/http.yaml
recorder: !include misc/recorder.yaml
influxdb: !include misc/influxdb.yaml

# AUTOMATIONS
automation: !include automations.yaml

# SCRIPTS
script: !include scripts.yaml

homeassistant:
  packages: !include_dir_named packages
