substitutions:
  name: everything-presence-one-7085ac
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret everything-presence-one-7085ac-api-encryption-key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
