substitutions:
  name: m5stack-atom-echo-539640
  friendly_name: M5Stack Atom Echo 539640
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret m5stack-atom-echo-api-encryption-key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
