esphome:
  name: talkie
  friendly_name: Talkie

esp32:
  board: featheresp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret talkie-api-encryption-key

ota:
  password: !secret talkie_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret talkie-hotspot-ssid
    password: !secret talkie-hotspot-password

captive_portal:
    
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: 13
    i2s_bclk_pin: 33
  - id: i2s_in
    i2s_lrclk_pin: 32
    i2s_bclk_pin: 22

speaker:
  - platform: i2s_audio
    id: external_speaker
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: 27
    mode: mono

media_player:
  - platform: i2s_audio
    name: Media Player
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: 27
    mode: mono
    on_play:
      light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 25%
        effect: pulse
    on_idle:
      light.turn_off:
        id: led

microphone:
  - platform: i2s_audio
    id: external_microphone
    adc_type: external
    i2s_audio_id: i2s_in
    i2s_din_pin: 14
    pdm: false

sensor:
  - platform: adc
    pin: A13
    id: battery_voltage
    name: "Battery Voltage"
    update_interval: 60s
    disabled_by_default: true
    entity_category: diagnostic
    attenuation: auto
    filters:
      - multiply: 2.0

  - platform: template
    name: Battery
    update_interval: 60s
    device_class: "battery"
    state_class: "measurement"
    unit_of_measurement: "%"
    accuracy_decimals: 2
    lambda: return 123-123/pow(1+pow(id(battery_voltage).state/3.7,80),0.165);
  

binary_sensor:
  - platform: gpio
    pin:
      number: 21
      mode:
        input: true
        pullup: true
    name: Push to talk Button
    disabled_by_default: true
    entity_category: diagnostic
    on_press:
        then:
          - voice_assistant.start:
    #on_release:
        #then:
          #- light.turn_on:
              #id: led
              #blue: 100%
              #red: 0%
              #green: 0%
              #brightness: 25%
              #effect: pulse
          #- voice_assistant.stop:

  - platform: gpio
    name: Change Assistant Button
    pin:
      number: 17
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        light.turn_on:
          id: led
          blue: 100%
          red: 100%
          green: 0%
          brightness: 25%     
    on_release:
        if:
          condition:
            media_player.is_idle:
          then:
            light.turn_off:
              id: led

voice_assistant:
  microphone: external_microphone
  speaker: external_speaker
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 25%
        effect: none
  on_start: 
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 25%
        effect: pulse 
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 25%
        effect: none
  on_tts_end:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 25%
        effect: pulse
  on_end:
    - delay: 1s
    - wait_until:
        not:
          speaker.is_playing:
    - light.turn_off: led
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness: 25%
        effect: none
    - delay: 1s
    - light.turn_off: led

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: Voice Assistant Led
    disabled_by_default: true
    entity_category: config
    pin: 16
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms
          max_brightness: 25%